[providers]
nodejs = "18"

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["cd server && npm ci --only=production"]

[phases.build]
cmds = ["cd server && npx prisma generate"]

[phases.start]
cmd = "cd server && npm start"
